// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVMx2QO7rAk6FmiDd5Me3S12DmG1z6CKY',
    appId: '1:997540631003:web:8999315ec9915c3d7917fe',
    messagingSenderId: '997540631003',
    projectId: 'flura-ka401',
    authDomain: 'flura-ka401.firebaseapp.com',
    storageBucket: 'flura-ka401.firebasestorage.app',
    measurementId: 'G-5ZYBDZRBYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTyCFWrXFmxcsTOl-xf3glNTe-04HhU6s',
    appId: '1:997540631003:android:f930a1fcc3adac147917fe',
    messagingSenderId: '997540631003',
    projectId: 'flura-ka401',
    storageBucket: 'flura-ka401.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-qpC0A9Kz7sNJ6jSin9n966ABAbZRhNk',
    appId: '1:997540631003:ios:bc1c0c84091515017917fe',
    messagingSenderId: '997540631003',
    projectId: 'flura-ka401',
    storageBucket: 'flura-ka401.firebasestorage.app',
    iosBundleId: 'com.example.projectFluorography',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-qpC0A9Kz7sNJ6jSin9n966ABAbZRhNk',
    appId: '1:997540631003:ios:bc1c0c84091515017917fe',
    messagingSenderId: '997540631003',
    projectId: 'flura-ka401',
    storageBucket: 'flura-ka401.firebasestorage.app',
    iosBundleId: 'com.example.projectFluorography',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVMx2QO7rAk6FmiDd5Me3S12DmG1z6CKY',
    appId: '1:997540631003:web:0c7b41c87ea9efc27917fe',
    messagingSenderId: '997540631003',
    projectId: 'flura-ka401',
    authDomain: 'flura-ka401.firebaseapp.com',
    storageBucket: 'flura-ka401.firebasestorage.app',
    measurementId: 'G-JE0XDJ0WMT',
  );

}